'use strict';
(() => {
const D = window.RESEARCH_DATA;
const el = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta = k => D.indicators.find(i => i.id === k);
const valid = o => o && o.value !== null && ['published','caution','rounded-zero'].includes(o.status);
const fmt = o => !o || o.value === null ? '—' : o.status === 'unreliable' ? '!!' : o.status === 'suppressed' ? 'NP' : `${Number(o.value).toFixed(1)}${o.status === 'caution' ? '†' : o.status === 'rounded-zero' ? ' (rounded)' : ''}`;
const signed = n => n === null ? '—' : `${n > 0 ? '+' : ''}${n.toFixed(1)}`;
const obs = (k,y,g='Overall') => D.observations.filter(o => o.series === k && (!y || o.year === y) && o.group === g);
const nat = (k,y) => obs(k,y)[0];
const source = (o, label) => `<a href="${esc(o.workbook)}" title="${esc(o.sheet+' · '+o.cell)}">${esc(label || o.sheet+' · '+o.cell)}</a>`;
const opts = (id, items) => el(id).innerHTML = items.map(([v,t]) => `<option value="${esc(v)}">${esc(t)}</option>`).join('');
const table = (headers,rows, cls='') => `<table class="research-table ${cls}"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>i===0?`<th scope="row">${c}</th>`:`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
function bars(rows) { return rows.map(({o,label})=>`<div class="bar-row"><span>${source(o,label)}</span><div class="track" aria-hidden="true"><div class="fill" style="width:${valid(o)?o.value:0}%"></div></div><strong>${fmt(o)}${valid(o)?'%':''}</strong></div>`).join(''); }
function plot(rows){
 const W=1040,H=305,L=47,R=22,T=25,B=55,x=y=>L+(parseInt(y)-2005)/(2024-2005)*(W-L-R),y=v=>H-B-v/100*(H-T-B);
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="National adoption by survey year. Values and source definitions are available in the table below.">`;
 for(let p=0;p<=100;p+=25)svg+=`<line class="plot-grid" x1="${L}" y1="${y(p)}" x2="${W-R}" y2="${y(p)}"/><text class="plot-label" x="${L-7}" y="${y(p)+4}" text-anchor="end">${p}%</text>`;
 for(let yr=2005;yr<=2024;yr++)if(yr%2===1||yr===2024)svg+=`<text class="plot-label" x="${x(String(yr))}" y="${H-B+26}" text-anchor="middle">${String(yr).slice(2)}–${String(yr+1).slice(2)}</text>`;
 const approved=rows.filter(o=>valid(o)&&o.decision==='A');
 if(approved.length===2&&approved[0].segment===approved[1].segment)svg+=`<line class="approved-line" x1="${x(approved[0].year)}" y1="${y(approved[0].value)}" x2="${x(approved[1].year)}" y2="${y(approved[1].value)}"/>`;
 rows.filter(valid).forEach((o,i)=>{const xx=x(o.year),yy=y(o.value),title=esc(`${o.year}: ${fmt(o)}%, ${o.decision}; ${o.sheet} ${o.cell}`);svg+=o.decision==='C'?`<path d="M ${xx} ${yy-5} l 5 5 -5 5 -5 -5 Z" class="timeline-point"><title>${title}</title></path>`:`<circle cx="${xx}" cy="${yy}" r="4.5" class="timeline-point ${o.decision==='A'?'approved':''}"><title>${title}</title></circle>`;svg+=`<text class="plot-value" x="${xx}" y="${yy+(i%2?18:-10)}" text-anchor="middle">${fmt(o)}</text>`;});
 return `<div class="plot-scroll">${svg}</svg></div>`;
}
function history(){const k=el('historyMetric').value,rows=obs(k).sort((a,b)=>a.year.localeCompare(b.year));el('historyChart').innerHTML=plot(rows);el('historyValues').innerHTML=table(['Wave','National %','Gate','Published measure / denominator / source'],rows.map(o=>{const r=D.reviews.find(r=>r.record_id===o.record_id);return [esc(o.year),fmt(o),o.decision,`${esc(r.exact_source_label)}<br>${esc(o.denominator)}<br>${source(o)}<br>${esc(r.evidence_excerpt)}`];}),'evidence-table');}
function dimension(reset){const dim=el('dimension').value,keys=D.indicators.filter(i=>i.dimension===dim).map(i=>i.id),years=[...new Set(D.observations.filter(o=>keys.includes(o.series)).map(o=>o.year))].sort();if(reset){opts('dimensionYear',years.map(y=>[y,y]));el('dimensionYear').value=years.at(-1);}const yr=el('dimensionYear').value,rows=D.observations.filter(o=>keys.includes(o.series)&&o.year===yr&&o.group==='Overall');el('dimensionChart').innerHTML=rows.length?bars(rows.map(o=>({o,label:meta(o.series).label}))):'<p class="empty">No selected source observations for this wave.</p>';el('dimensionContext').textContent=`${yr} · ${dim} · All businesses in the survey scope. Each bar is a separate published measure; click its label for the workbook. ${dim==='Advanced technologies'?'Paid cloud and broad cloud are different measures. ':''}${dim==='Digital value'?'Reported outcomes associated with ICT use, not causal effects. ':''}This is a within-wave profile, not a maturity score.`;}
function size(){const k=el('sizeMetric').value,c=D.changes.find(c=>c.series===k);el('sizeChart').innerHTML=['2021-22','2024-25'].map(yr=>{const gap=D.gaps.find(g=>g.year===yr&&g.series===k);return `<div><h3>${yr}</h3>${bars(obs(k,yr,'Employment size').map(o=>({o,label:o.category})))}<p class="mini-label">200+ minus 0–4 gap <span class="gap-number">${signed(gap.gap)} pp</span></p></div>`;}).join('');el('sizeChange').textContent=`National adoption: ${c.start_value.toFixed(1)}% → ${c.end_value.toFixed(1)}% (${signed(c.change_pp)} pp). Size gap change: ${signed(c.size_gap_change_pp)} pp. Both the national rise and the widening gap remain when flagged inputs are excluded.`;}
function industry(){const k=el('industryMetric').value,rows=D.persistence.filter(p=>p.series===k).sort((a,b)=>a.gap_2024_25-b.gap_2024_25);const heat=(v,o)=>`<td style="background:${v<0?'#e5edf5':'#e2f0e7'}">${source(o,signed(v)+(o.status==='caution'?'†':''))}</td>`;el('industryTable').innerHTML=`<table class="research-table"><thead><tr><th scope="col">Industry</th><th scope="col">2021–22 gap (pp)</th><th scope="col">2024–25 gap (pp)</th><th scope="col">Below national</th><th scope="col">Unflagged waves</th></tr></thead><tbody>${rows.map(p=>{const a=obs(k,'2021-22','Industry').find(o=>o.category===p.industry),b=obs(k,'2024-25','Industry').find(o=>o.category===p.industry);return `<tr><th scope="row">${esc(p.industry)}</th>${heat(p.gap_2021_22,a)}${heat(p.gap_2024_25,b)}<td>${p.below} / ${p.waves}</td><td>${p.unflagged_waves} / ${p.waves}</td></tr>`;}).join('')}</tbody></table>`;el('industryStory').textContent=`${rows.filter(p=>p.below===2).length} of ${rows.length} matched industries are below the national ${meta(k).label.toLowerCase()} rate in both observed waves. National benchmarks: ${fmt(nat(k,'2021-22'))}% and ${fmt(nat(k,'2024-25'))}%. This is recent recurrence, not a long-run ranking.`;}
function innovation(){const k=el('innovationMetric').value,g=el('innovationGroup').value,rows=D.innovation.filter(a=>a.series===k&&a.group===g);el('innovationTable').innerHTML=table(['2018–19 category','Innovation-active %','Non-active %','Difference (pp)','Source'],rows.map(a=>[esc(a.category),fmt({value:a.active,status:a.active_status}),fmt({value:a.nonactive,status:a.nonactive_status}),signed(a.gap)+(a.status==='caution'?'†':''),`<a href="${esc(a.workbook)}">${esc(a.sheet+' · '+a.active_cell+' / '+a.nonactive_cell)}</a>`]));}
opts('historyMetric',['internet','web','social','placed','received'].map(k=>[k,meta(k).label]));
opts('dimension',D.dimensions.map(d=>[d,d]));
opts('innovationMetric',['internet','web','social','placed','received'].map(k=>[k,meta(k).label]));el('innovationMetric').value='received';
el('headlineCards').innerHTML=[['internet','Connected to the internet'],['received','Received online orders'],['cloud','Used cloud technology'],['ai','Used artificial intelligence']].map(([k,label])=>{const o=nat(k,'2024-25');return `<article class="kpi"><p>${esc(label)}</p><strong>${fmt(o)}%</strong><small>2024–25 · all businesses<br>${source(o)}</small></article>`;}).join('');
el('historyStory').textContent=`Internet access was ${fmt(nat('internet','2006-07'))}% in the 2006–07 snapshot and ${fmt(nat('internet','2018-19'))}% in 2018–19. The 2024–25 any-connection measure is ${fmt(nat('internet','2024-25'))}%. This pattern suggests widespread diffusion, but these endpoints are not an approved continuous series. Online orders need particular care: the 2019–20 to 2021–22 difference cannot be read as a clean fall in adoption across the survey redevelopment.`;
el('sizeStory').textContent='Between 2021–22 and 2024–25, the national shares using social media and receiving online orders both rose. In each case, the gap between 200+ and 0–4 employee businesses also widened. These are the two recent comparisons approved in this study; they do not establish a long-run convergence trend.';
el('constraintStory').textContent=`In 2024–25, ${fmt(nat('skills','2024-25'))}% of businesses reported insufficient skills as an ICT constraint, ${fmt(nat('funds','2024-25'))}% reported lack of funds, and ${fmt(nat('benefits','2024-25'))}% reported uncertainty about costs and benefits. No single barrier replaces the others.`;
el('constraintChart').innerHTML=['2021-22','2024-25'].map(y=>`<div><h3>${y} · separate snapshot</h3>${bars(['skills','funds','benefits','technology','knowledge'].map(k=>({o:nat(k,y),label:meta(k).label})))}</div>`).join('');
el('auditCount').textContent=`${D.verified_numeric_cells.toLocaleString()} selected numeric source cells checked; ${D.observations.length.toLocaleString()} observations and ${D.reviews.length} selected-item decisions. Every plotted estimate links to its original workbook, with sheet and cell coordinates in the link or its tooltip.`;
el('limitations').innerHTML=D.limitations.map(s=>`<li>${esc(s)}</li>`).join('');
el('absSource').href=D.sources.abs_recent;el('method2021').href=D.sources.methodology_2021;el('method2024').href=D.sources.methodology_2024;
for(const [id,fn] of [['historyMetric',history],['dimension',()=>dimension(true)],['dimensionYear',()=>dimension(false)],['sizeMetric',size],['industryMetric',industry],['innovationMetric',innovation],['innovationGroup',innovation]])el(id).addEventListener('change',fn);
history();dimension(true);size();industry();innovation();
})();
