'use strict';
(() => {
 const D=window.AI_RESEARCH,el=id=>document.getElementById(id);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const valid=(o,strict=false)=>o&&o.value!==null&&(strict?['published','rounded-zero']:['published','caution','rounded-zero']).includes(o.status);
 const fmt=o=>!o?'—':o.status==='suppressed'?'NP':o.status==='unreliable'?'!!':o.value===null?'—':o.value.toFixed(1)+(o.status==='caution'?'†':o.status==='rounded-zero'?' (rounded)':'');
 const source=(o,label)=>`<a href="${esc(o.workbook)}" title="${esc(o.sheet+' · '+o.cell)}">${esc(label||o.sheet+' · '+o.cell)}</a>`;
 const ai=(group)=>D.observations.filter(o=>o.variable==='ai'&&o.year==='2024-25'&&(!group||o.group===group));
 const table=(heads,rows)=>`<table class="ai-table"><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((c,i)=>i?`<td>${c}</td>`:`<th scope="row">${c}</th>`).join('')}</tr>`).join('')}</tbody></table>`;
 function bars(rows,benchmark=false,labels=false){return rows.map(o=>`<div class="bar-row ${o.status==='caution'?'caution':''}"><span>${source(o,labels?o.label:o.category)}</span><div class="track" aria-hidden="true">${benchmark?`<i class="benchmark" style="left:${D.national.value}%"></i>`:''}<div class="fill" style="width:${valid(o)?o.value:0}%"></div></div><strong>${fmt(o)}${valid(o)?'%':''}</strong></div>`).join('');}
 const industryRows=()=>ai('Industry').filter(o=>valid(o,el('industryFlags').value==='strict'));
 function industry(){let rows=industryRows();if(el('industryOrder').value==='rank')rows.sort((a,b)=>b.value-a.value);el('industryBars').innerHTML=bars(rows,true);const values=rows.map(o=>o.value),range=values.length?Math.max(...values)-Math.min(...values):null;el('industrySensitivity').textContent=`${rows.length} usable industries. Observed range: ${range===null?'unavailable':range.toFixed(1)+' percentage points'}. ${el('industryFlags').value==='strict'?'Flagged estimates excluded.':'Usable cautions included.'}`;el('industryValues').innerHTML=table(['Industry','AI use (%)','Gap to national (pp)','Source'],rows.map(o=>[esc(o.category),fmt(o),(o.value-D.national.value).toFixed(1),source(o)]));}
 function geo(){const group=el('geoGroup').value;el('geoBars').innerHTML=bars(ai(group));el('geoNote').textContent=group==='Location'?'Location categories include overlapping capital-city totals and components. Do not add them together. All rates refer to businesses in the named location category.':'State/territory of main operation. Northern Territory carries a source caution; retain it as context, not a headline ranking.';}
 function context(reset){const group=el('contextGroup').value,rows=ai(group);if(reset)el('contextCategory').innerHTML=rows.map(o=>`<option>${esc(o.category)}</option>`).join('');el('contextBars').innerHTML=bars(D.observations.filter(o=>o.year==='2024-25'&&o.group===group&&o.category===el('contextCategory').value),false,true);}
 const size=ai('Employment size'),disp=D.dispersion[0];
 el('aiCards').innerHTML=[['National AI adoption',fmt(D.national)+'%','All businesses in survey scope'],['Micro businesses',fmt(size[0])+'%','0–4 persons employed'],['Large businesses',fmt(size[3])+'%','200+ persons employed'],['Large minus micro',D.gaps[0].gap_pp.toFixed(1)+' pp','Descriptive adoption gap']].map(([label,value,note])=>`<article class="kpi"><p>${esc(label)}</p><strong>${esc(value)}</strong><small>2024–25 · ${esc(note)}</small></article>`).join('');
 el('sizeNarrative').textContent=`Reported AI use rises across the four published size bands: ${size.map(o=>fmt(o)+'%').join(', ')}. The difference is ${D.gaps[0].gap_pp.toFixed(1)} percentage points between large and micro businesses. This is a group-level association, not an effect of business size.`;
 el('sizeBars').innerHTML=bars(size);el('gapCards').innerHTML=D.gaps.map(g=>`<div><p class="mini-label">${esc(g.comparison)}</p><div class="gap-number">${g.gap_pp.toFixed(1)} pp</div><p>${g.large_percent.toFixed(1)}% minus ${g.comparison_percent.toFixed(1)}%. ${g.unflagged_inputs?'Both estimates are unflagged.':'Contains a flagged input.'}</p></div>`).join('');
 el('industryNarrative').textContent=`Across ${disp.industries} industries, AI use ranges from ${disp.minimum_percent.toFixed(1)}% in ${disp.minimum_industry} to ${disp.maximum_percent.toFixed(1)}% in ${disp.maximum_industry}. The ${disp.range_pp.toFixed(1)}-point range is unchanged when flagged estimates are excluded.`;
 const history=D.observations.filter(o=>o.variable==='ai'&&o.group==='Overall');el('historyCards').innerHTML=history.map(o=>`<article class="ai-history"><h3>${esc(o.year)}</h3><strong>${fmt(o)}%</strong><p>${o.temporal_gate}: separate snapshot</p>${source(o)}</article>`).join('');
 el('historyAudit').innerHTML=table(['Wave','Original item / examples','Decision'],D.audit.filter(a=>a.variable==='ai').map(a=>[esc(a.year),esc(a.original_wording+' '+JSON.parse(a.examples).join(' ')),esc(a.temporal_gate+': '+a.rationale)]));
 el('innovationEvidence').textContent=D.evidence.finding;el('innovationSource').href=D.evidence.source;
 el('verification').textContent=`${D.verified_cells} numeric workbook cells verified, ${D.observations.length} observations retained, and ${D.audit.length} item/year decisions recorded. This includes all 35 published AI observations for 2024–25, same-wave digital context and earlier AI snapshots.`;
 el('industryOrder').addEventListener('change',industry);el('industryFlags').addEventListener('change',industry);el('geoGroup').addEventListener('change',geo);el('contextGroup').addEventListener('change',()=>context(true));el('contextCategory').addEventListener('change',()=>context(false));industry();geo();context(true);
})();
